import type { Metadata } from "next";
import { Oswald } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import { FitsProvider } from "@/context/FitsContext";
import { ToastContainer } from "react-toastify";
import Footer from "@/components/shared/Footer";

const oswald = Oswald({
  variable: "--font-oswald",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${oswald.variable} ${oswald.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <FitsProvider>
          <Navbar />
          {children}
          <Footer />
          <ToastContainer />
        </FitsProvider>
      </body>
    </html>
  );
}
