"use client";

import { useEffect, useState } from "react";

const STORAGE_KEY = "fitlog-ai-suggestions";

export default function SettingsPage() {
  const [enabled, setEnabled] = useState(false);
  const [ready, setReady] = useState(false);

  useEffect(() => {
    setEnabled(window.localStorage.getItem(STORAGE_KEY) === "true");
    setReady(true);
  }, []);

  function updateEnabled(nextEnabled: boolean) {
    setEnabled(nextEnabled);
    window.localStorage.setItem(STORAGE_KEY, String(nextEnabled));
  }

  return (
    <main className="flex-1 bg-[#10110f] px-5 py-12 text-white sm:px-8">
      <section className="mx-auto max-w-3xl">
        <p className="text-xs font-bold uppercase tracking-[0.22em] text-[#a3e635]">Preferences</p>
        <h1 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">Settings</h1>
        <p className="mt-3 max-w-xl text-sm leading-6 text-zinc-400">Customize how FitLog helps you plan and track your workouts.</p>

        <div className="mt-9 rounded-2xl border border-zinc-800 bg-[#171816] p-6 sm:p-8">
          <div className="flex items-start justify-between gap-6">
            <div>
              <div className="flex items-center gap-2">
                <h2 className="text-lg font-semibold">AI workout suggestions</h2>
                <span className="rounded-full border border-[#405126] bg-[#20291a] px-2 py-0.5 text-[10px] font-bold uppercase tracking-wider text-[#a3e635]">Beta</span>
              </div>
              <p className="mt-2 max-w-lg text-sm leading-6 text-zinc-400">Get suggested exercises and next steps based on your workout log.</p>
            </div>
            <input
              aria-label="Enable AI workout suggestions"
              type="checkbox"
              className="toggle mt-1 shrink-0 border-zinc-600 bg-zinc-700 checked:border-[#a3e635] checked:bg-[#a3e635] checked:text-black"
              checked={enabled}
              disabled={!ready}
              onChange={(event) => updateEnabled(event.target.checked)}
            />
          </div>

          <div className="mt-6 rounded-xl border border-zinc-800 bg-[#111210] p-5">
            <p className="text-xs font-semibold uppercase tracking-wider text-zinc-500">{enabled ? "Suggestions are on" : "Suggestions are off"}</p>
            {enabled ? (
              <ul className="mt-4 space-y-3 text-sm text-zinc-300">
                <li className="flex gap-3"><span className="text-[#a3e635]">↗</span><span>Try adding a 5-minute warm-up before your next strength session.</span></li>
                <li className="flex gap-3"><span className="text-[#a3e635]">↗</span><span>Log your sets and reps to get more useful workout suggestions.</span></li>
              </ul>
            ) : (
              <p className="mt-3 text-sm leading-6 text-zinc-500">Turn this on to see workout suggestions in FitLog.</p>
            )}
          </div>
          <p className="mt-5 text-xs leading-5 text-zinc-500">Your preference is saved on this device. Suggestions shown here are examples and are not generated by an AI service.</p>
        </div>
      </section>
    </main>
  );
}
